passes: Add InstructionFolderPass
lifting-bits/anvill pull request #140
Opened 2021-03-19 18:20 UTC by alessandrogario

2021-03-22 20:10 UTC, kumarak commented
@alessandrogario, I think the type compare for the global variable will fail because it will be of pointer type but the type you are passing is `i8`.  Maybe you would like to compare it with the `symbolic_value->getValueType()`.  Sorry I was not able to add comments on the code because the changes are not from this PR.

https://github.com/lifting-bits/anvill/blob/alessandro/feature/implement-inst-combine-pass/libraries/anvill_passes/src/BaseFunctionPass.h#L183

2021-03-22 22:41 UTC, pgoodman requested changes

2021-03-22 22:41 UTC, pgoodman commented on libraries/anvill_passes/src/InstructionFolderPass.cpp
> +      instr->eraseFromParent();
`function_changed = true;`

2021-03-22 22:41 UTC, pgoodman commented on libraries/anvill_passes/src/InstructionFolderPass.cpp
> +    replaced_instr_list.push_back(user_instr);
This is redundant; `replaceAllUsesWith` means there are no uses left, so you can do `replaced_instr->eraseFromParent();` here without the later loop and `use_empty` check.

2021-03-22 22:41 UTC, pgoodman commented on libraries/anvill_passes/src/InstructionFolderPass.cpp
> +    replaced_instr_list.push_back(user_instr);
If you want to be super safe (maybe there is some weird PHI node issue) then what I'd recommend is that `replace_instr_list` be a list a `std::pair`, and you `emplace_back(user_instr, replacement)`, then in your later loop, you do:

```c++
for (auto [instr, replacement_instr] : replaced_instr_list) {
  instr->replaceAllUsesWith(replacement_instr);
  instr->eraseFromParent();
}
```

2021-03-22 22:41 UTC, pgoodman commented on libraries/anvill_passes/src/InstructionFolderPass.cpp
> +    user_instr->replaceAllUsesWith(replacement);
Ditto on the above comment.

2021-03-22 22:41 UTC, pgoodman commented on libraries/anvill_passes/src/InstructionFolderPass.cpp
> +      llvm::dyn_cast<llvm::BinaryOperator>(binary_op_instr)->getOpcode();
Just use `binary_op_instr->getOpcode()`

2021-03-23 00:01 UTC, alessandrogario commented
> @alessandrogario, I think the type compare for the global variable will fail because it will be of pointer type but the type you are passing is `i8`. Maybe you would like to compare it with the `symbolic_value->getValueType()`. Sorry I was not able to add comments on the code because the changes are not from this PR.
> 
> https://github.com/lifting-bits/anvill/blob/alessandro/feature/implement-inst-combine-pass/libraries/anvill_passes/src/BaseFunctionPass.h#L183

Thanks for the review! I will start a new branch to fix it and look at an issue i found with the undefined behaviour sanitizer in the stack recovery function pass

2021-03-23 00:08 UTC, pgoodman approved these changes

2021-03-23 00:25 UTC, pgoodman commented
> > @alessandrogario, I think the type compare for the global variable will fail because it will be of pointer type but the type you are passing is `i8`. Maybe you would like to compare it with the `symbolic_value->getValueType()`. Sorry I was not able to add comments on the code because the changes are not from this PR.
> > https://github.com/lifting-bits/anvill/blob/alessandro/feature/implement-inst-combine-pass/libraries/anvill_passes/src/BaseFunctionPass.h#L183
> 
> Thanks for the review! I will start a new branch to fix it and look at an issue i found with the undefined behaviour sanitizer in the stack recovery function pass

Ah indeed, that does need to a `getValueType` or maybe `getElementType`. There's a Remill API for this :-P https://github.com/lifting-bits/remill/blob/3808e9951db8a7332f361d802de5815cb2877571/include/remill/BC/Compat/GlobalValue.h#L24

2021-03-23 00:25 UTC, merged