fix replace memory op for float80
lifting-bits/anvill pull request #255
Opened 2021-09-02 23:11 UTC by kumarak

Fix lowering of memory op intrinsics for float80

Ref: https://github.com/lifting-bits/remill/pull/539

2021-09-03 18:00 UTC, pgoodman requested changes

2021-09-03 18:42 UTC, kumarak commented on libraries/anvill_passes/src/InstructionFolderPass.cpp
> +      if (cond_vt->getElementType() !=
Returning type checks with `IntegerType` will not cover all cases. There could be a mismatch in number of elements and vector select folding will fail in such cases as well. 

```  
  %181 = select <16 x i1> %164, <16 x i8> zeroinitializer, <16 x i8> %180
  %182 = bitcast <16 x i8> %180 to <2 x i64>
  %183 = bitcast <16 x i8> %181 to <2 x i64>
```

In the above case, there will be mismatch of the destination type elements count causing the folding to fail.

2021-09-03 21:52 UTC, kumarak commented on libraries/anvill_passes/src/LowerRemillMemoryAccessIntrinsics.cpp
> +  CopyMetadataTo(call_inst, val);
This copies the metadata to store instruction. I updated it to assign to a variable and use that to copy the metadata.

2021-09-10 16:31 UTC, pgoodman commented on libraries/anvill_passes/src/InstructionFolderPass.cpp
> +      if (cond_vt->getElementType() !=
Are there any vector select cases that we actually handle?

2021-09-10 16:34 UTC, pgoodman approved these changes

2021-09-10 16:35 UTC, pgoodman commented
@kumarak can you enable the now-passing tests in this PR, and look into the failing test?

```
[!] There were [1] failures on x86:
`Instructions.cpp:2873`: `1` failures
    /__w/anvill/anvill/src/anvill/angha-test-1k/results/x86/python/success/freebsd/usr.bin/systat/extr_iostat.c_devstats.elf/output.json
Ignored 3 tests.
    2 ignored tests are passing! They are:
    /__w/anvill/anvill/src/anvill/angha-test-1k/results/x86/python/success/postgres/src/backend/access/nbtree/extr_nbtsort.c__bt_parallel_heapscan.elf/output.json
    /__w/anvill/anvill/src/anvill/angha-test-1k/results/x86/python/success/sumatrapdf/ext/libwebp/src/enc/extr_picture_psnr_enc.c_AccumulateLSIM.elf/output.json
```

2021-09-14 13:45 UTC, pgoodman approved these changes

2021-09-14 13:45 UTC, merged