Callsite override
lifting-bits/anvill pull request #398
Opened 2023-10-03 14:33 UTC by Ninja3047

2023-10-03 15:05 UTC, 2over12 requested changes

2023-10-03 15:05 UTC, 2over12 commented on lib/Passes/RemoveCallIntrinsics.cpp
> +    std::optional<CallableDecl> maybe_decl;
Shouldnt this be initialized to spec.FunctionAt folded address ie. the default is we just call the address and dont have to rely on the override if one doesnt exist?

2023-10-03 15:20 UTC, Ninja3047 commented on lib/Passes/RemoveCallIntrinsics.cpp
> +    std::optional<CallableDecl> maybe_decl;
https://github.com/lifting-bits/anvill/pull/398/commits/4e83da7f9ef3e614bf1b41af54ed9a6b262d1b18

2023-10-03 15:24 UTC, 2over12 approved these changes

2023-10-04 11:02 UTC, tetsuo-cpp approved these changes
LGTM codewise, I'm missing context around this change though. What's this solving?

2023-10-04 11:02 UTC, tetsuo-cpp commented on lib/Specification.cpp
> +Specification::CallSiteAt(std::pair<std::uint64_t, std::uint64_t> loc) const {
Don't need to copy here: `const std::pair<std::uint64_t, std::uint64_t>&`

2023-10-04 11:02 UTC, tetsuo-cpp commented on lib/Passes/RemoveCallIntrinsics.cpp
> +            callable_decl = override_decl;
Shared pointer doesn't need to be copied: `callable_decl = std::move(override_decl)`

2023-10-04 11:02 UTC, tetsuo-cpp commented on lib/Passes/RemoveCallIntrinsics.cpp
> +            bb_ctx_ref.has_value()) {
I'm not super familiar with these helpers, but is it expected that we can get a None here given that we know we're looking at a basic block function?

2023-10-04 11:02 UTC, tetsuo-cpp commented on lib/Utils.cpp
> +                                         llvm::Instruction &instr) {
`const llvm::Instruction &`

2023-10-04 14:37 UTC, Ninja3047 commented
> LGTM codewise modulo some C++ nits, I'm missing context around this change though. What's this solving?

the main use case is for fixing varargs functions
right now when we see a varargs function, we don't necessarily correctly detect the number of parameters actually used. ghidra has the ability to override a function call at a particular call site but we weren't using that information before. this pr makes it so we fetch that information (which was already in the spec) and apply it in the remove call intrinsics pass.

2023-10-04 23:58 UTC, tetsuo-cpp approved these changes
Awesome, thanks for the added context.

2023-10-04 23:59 UTC, merged