New visitor-style machine code lifter
lifting-bits/anvill pull request #45
Opened 2020-09-24 15:00 UTC by surovic

This PR replaces the old machine code lifter based on `remill::TraceLifter` with a new custom visitor-style worklist-based lifter. The lifter does *not* perform recursive descent based on callsites. Only functions (and global variables) specified by a JSON specification are lifted. The old lifter is "archived" in `LegacyLifter.(h|cpp)` for reference purposes. The old lifter is *not* compiled during build.

The new lifter lives in `MCToIRLifter.(h|cpp)`. The `Lift.(h|cpp)` files only contain code that inlines "remill-style lifted functions" into "high-level ABI functions".

2020-09-24 18:12 UTC, pgoodman requested changes

2020-09-28 11:45 UTC, surovic commented on JSON.cpp
> +  auto semantics = remill::LoadArchSemantics(arch);
Removed. Is there a better way now to do the above? :eyes:

2020-09-28 11:54 UTC, surovic commented on JSON.cpp
> +    llvm::Value *gval = nullptr;
Made a separate issue for this, since it requires a bit more code. What about using `GlobalAlias` for both data and functions?

2020-09-28 15:51 UTC, pgoodman commented on JSON.cpp
> +  auto semantics = remill::LoadArchSemantics(arch);
You mean, to load the architecture semantics files? If this is the question then there probably is a better way. The way it works right now is a slight kludge, which was the easiest approach that I could think of when I first made it. Eventually it'd be nice to have a search path feature, with the current hard-coded ones remaining as backups or something like that.

2020-09-28 15:51 UTC, pgoodman approved these changes

2020-09-28 15:51 UTC, merged